USE db_blog;
CREATE TABLE Admin (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PublicId CHAR(25) NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    UserName VARCHAR(255) NOT NULL 
    Password VARCHAR(255) NOT NULL,
    Birthday DATE NOT NULL,
    Settings JSON NOT NULL DEFAULT '{}',
    Perms JSON NOT NULL DEFAULT '{}',
    CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedOn DATETIME ON UPDATE CURRENT_TIMESTMAP NOT NULL,
    UNIQUE(UserName)
)

CREATE TABLE Post (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PublicId CHAR(25) NOT NULL,
    PublishDate DATETIME,
    Title VARCHAR(255) NOT NULL,
    Body TEXT NOT NULL,
    Status MEDIUMINT NOT NULL,
    CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedOn DATETIME ON UPDATE CURRENT_TIMESTMAP NOT NULL,
)

CREATE TABLE PostAdmin (
    Id MEDIUMINT,
    PostId MEDIUMINT,
    AdminId MEDIUMINT,
    CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedOn DATETIME ON UPDATE CURRENT_TIMESTMAP NOT NULL,
)

CREATE TABLE PostStatus (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
    Name
    PublicFacingName 
    CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedOn DATETIME ON UPDATE CURRENT_TIMESTMAP NOT NULL,
)
-- ALTER TABLE Orders
-- ADD FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);
ALTER TABLE PostAdmin
    ADD FOREIGN KEY (PostId) REFERENCES Post(Id),
    ADD FOREIGN KEY(AdminId) REFERENCES Admin(Id);